### ISSUE TITLE
(minor) incorrect options listed in help message when using --external-ca

### ISSUE THREAD

**Issue by tkent** [freeipa/freeipa-container#247]
**Version:** `freeipa-server:centos-7`

When installing a new FreeIPA environment and using the `--external-ca` option, a helpful message is output after the CSR is generated. The message is:

```
The next step is to get /root/ipa.csr signed by your CA and re-run /usr/sbin/ipa-server-install as:
/usr/sbin/ipa-server-install --external-cert-file=/path/to/signed_certificate --external-cert-file=/path/to/external_ca_certificate
```

The duplicate `--external-cert-file` options in the message should actually be `--external_cert_file` and `--external_ca_file`

So the whole thing would be
```
The next step is to get /root/ipa.csr signed by your CA and re-run /usr/sbin/ipa-server-install as:
/usr/sbin/ipa-server-install --external_cert_file=/path/to/signed_certificate --external_ca_file=/path/to/external_ca_certificate
```

Obviously, this is an extremely minor thing.

**Comment by adelton** [comment]
Well, based on https://www.freeipa.org/page/V4/Installer_CA_options_usability_improvements which sadly hasn't been updated since 2015 but which points to https://pagure.io/freeipa/issue/4480 which in turn points to https://pagure.io/freeipa/c/3aa0731fc660ea3d111a44926ab5dea71dc510e7, the `--external-cert-file` is now the preferred option.

Moreover, that message is actually printed by the `ipa-server-install` itself, it's not something specific to the FreeIPA containerization.

I believe the message is actually correct but if you feel otherwise, please report it at https://pagure.io/freeipa/issues.

**Comment by stlaz** [comment]
The message is indeed correct.

**Comment by tkent** [comment]
@adelton @stlaz 

Sorry for the noise! I obviously wasn't thorough enough when validating the problem. 

I thought the message seemed wrong and cross checked with the man page on an older version of freeipa. Since the now-outdated options still work, it didn't even dawn on me check the `--help` output of the current `ipa-server-install` version.

Anyway, sorry again for the noise.
