### ISSUE TITLE
hostnamectl error while using ipa-server-install-options

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [freeipa/freeipa-container#265]
Not sure if this issue was me doing something wrong or is an actual bug. While trying to use ipa-server-install-options of
```
--realm=EXAMPLE.LOCAL
--domain=example.local
--ds-password=dspassword
--admin-password=adminpassword
--hostname=ipa01.example.local
--setup-dns
--forwarder=8.8.8.8
--forwarder=8.8.4.4
--no-reverse
--unattended
```

and docker run of
```
docker run \ 
    --name ipa01 \ 
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \ 
    -ti \
    --tmpfs /run \ 
    --tmpfs /tmp \
    -v /var/lib/ipa-data:/data:Z \
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
    -h ipa01 \
    -e DEBUG_TRACE=1 \
    -e DEBUG_NO_EXIT=1 \
    freeipa-server 
```
I was seeing hostnamectl error simular to other issues already reported here. Once I removed `--hostname=ipa01.example.local` from ipa-server-install-options and added `-e IPA_SERVER_HOSTNAME=ipa01.example.local \` to the run cmd the container setup completed successfully. 

Other details:
host: Amazon Linux 2
arch: ARM
docker version: 18.06.1-ce, build e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
freeipa-server image build: docker build -t freeipa-server . # built on 20190406

Everything is working as expected at this point. Just wanted to pass this along and make sure I'm not doing something wrong. We are going to be using this long term for 2FA on containerized web sites. I will be setting up replica's today, hopefully that goes smoother. =)

**Comment by adelton** [comment]
I believe that what you describe is expected.
The `ipa-server-install --hostname ...` option causes `hostnamectl` to be called and when the container is running unprivileged, it will fail. 
If you want to have things nice, use `docker run -h ...` option to set the hostname already when the container is created.
But it turns out that the hostname in the FreeIPA server container does not really matter, so the `IPA_SERVER_HOSTNAME` approach also works.

**Comment by tkontogi** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1353831

**Comment by adelton** [comment]
Let's assume that using `docker run -h ...` helped.
