### ISSUE TITLE
Create initial tag for repo

### ISSUE THREAD

**Issue by tylerauerbeck** [freeipa/freeipa-container#269]
Would it be possible to create an initial tag for this repo? We would like to to reference some of the templates here (specifically the Openshift ones) without having to keep our own copy, but are also a little hesitant to rely on pointing directly to master.

**Comment by adelton** [comment]
If the OpenShift templates in their current form work for you, you can reference them using the current master commit 5e55ee8a62e7c51bf8c1805b33425f48e2d8f44e without getting any subsequent changes in -- for example https://raw.githubusercontent.com/freeipa/freeipa-container/5e55ee8a62e7c51bf8c1805b33425f48e2d8f44e/freeipa-server-openshift.json

I'm hesitant to do any tagging in this repository. I don't want to come up with artificial versioning, we support multiple FreeIPA versions with these Dockerfiles and content, and since the FreeIPA and OS bits change, they can get broken at any time.
