### ISSUE TITLE
deriving image from freeipa-server 

### ISSUE THREAD

**Issue by bpinsard** [freeipa/freeipa-container#305]
I am experiencing a problem when extending the image.

```
#FROM freeipa/freeipa-server:fedora-30

RUN dnf install -y letsencrypt cronie cronie-anacron && \
	dnf clean all
``` 

This give the following error at build:
```
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM freeipa/freeipa-server:fedora-30
 ---> 001a33fe331f
Step 2/4 : RUN dnf install -y letsencrypt cronie cronie-anacron && 	dnf clean all
 ---> Running in 7d82e9e60dc6
Fedora Modular 30 - x86_64                      0.0  B/s |   0  B     00:00    
Error: Failed to download metadata for repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (77): Problem with the SSL CA cert (path? access rights?) for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none]
The command '/bin/sh -c dnf install -y letsencrypt cronie cronie-anacron && 	dnf clean all' returned a non-zero code: 1
 ```

If I bypass this error by adding 
`RUN echo 'sslverify=0' >> /etc/dnf/dnf.conf`
before the dnf install, it downloads the packages then dnf crashes with a lots of this type of errors:
```
Error in <scriptsomething> scriptlet in rpm package <package>
```

If I use the image on which freeipa-server is based
```
FROM registry.fedoraproject.org/fedora:30
```
as the base image, none of these errors happen.

Is there something broken in the way the container is built, or are we not supposed to extend the container?

Thanks for you help.

**Comment by adelton** [comment]
The short answer is that the freeipa-server is not really prepared with extendability as its goal -- the primary goal is ease of use with persistent storage. So the initial question for what you seem to try to achieve might be: could it be done with a separate container and running them both side by side in a pod in OpenShift or Kubernetes?

However, it is possible to extend the image, so if you prefer or need to have it all in one container, here's some info to get you started.

The freeipa-server container is prepared in such a way that all data and config files will be stored under `/data` volume, and the image has symlinks in respective places to point under this `/data` location. But the volume is empty when you run a container, that's why `/etc/pki/tls/certs/ca-bundle.crt` is found not existing:
```
$ docker run --rm freeipa/freeipa-server:fedora-30 bash -c 'ls -la /etc/pki/tls/certs/ca-bundle.crt /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem'
lrwxrwxrwx. 1 root root 49 Jan 31  2019 /etc/pki/tls/certs/ca-bundle.crt -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
ls: cannot access '/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem': No such file or directory
$ docker run --rm freeipa/freeipa-server:fedora-30 bash -c 'ls -dla /etc/pki/ca-trust'
lrwxrwxrwx. 1 root root 22 Dec  9 11:39 /etc/pki/ca-trust -> /data/etc/pki/ca-trust
```

The entrypoint of the freeipa-server container is the `/usr/local/sbin/init` script which upon the first invocation populates the (empty) volume from `/data-template`, where the original content is stored in the image.

To extend the freeipa-server image, you likely need to populate that `/data` location with the content that whatever you are running (dnf, in this case) expects there. So your step
```
RUN dnf install -y letsencrypt cronie cronie-anacron && \
	&& dnf clean all
```
likely needs to change to something like
```
RUN ( cd /data-template && cp -rp . /data ) \
	&& ( cd /tmp-template && cp -rp . /tmp ) \
	&& dnf install -y letsencrypt cronie cronie-anacron && dnf clean all \
	&& ( cd /data && cp -rp . /data-template )
```
Here we populate `/data` (and `/tmp`, it's the same story) from the `*-template` directory, so that symlinks play nicely, we run the command that we want, and then we put the content back to `*-template`, to store any new data that the packages might have brought.

When you build such an image (and if you diff the new things in `/data`), you will find
```
/data/etc/pam.d/crond
/data/etc/sysconfig/certbot
/data/etc/sysconfig/crond
/data/etc/sysconfig/run-parts
/data/etc/systemd/system/container-ipa.target.wants/crond.service
```
there, and then copied to `/data-template`, to be used to populate the volume upon the first container invocation.

**Comment by adelton** [comment]
However, consider what will happen when later you rebuild with newer packages and say the content of `/etc/sysconfig/crond` (brought by rpm) will have changed in the new version.

The old version of the file had been copied from `/data-volume/etc/sysconfig/crond` to the volume (mounted under `/data`) upon the first container run. So in normal installation on a host, rpm would have replaced that file upon rpm upgrade transaction. Except when that file is marked as `%config`. But in case that config file is marked as `%config(noreplace)`, it would only be replaced during rpm upgrade if it was not changed on the disk since the state created by the previous version of the package. (More details at https://www.cl.cam.ac.uk/~jw35/docs/rpm_config.html).

But in container world, there is no rpm upgrade. Each container image build is a fresh rpm install transaction with whatever packages are currently available, and the build has no idea what the previous container image was and what package versions it contained.

The freeipa-server image has a logic in `/usr/local/bin/populate-volume-from-template` invoked from `/usr/local/sbin/init` during upgrades (when the volume was last used with different image than the currently running one) which uses stored `%config` information from the previous version to do what normally would be done by rpm upgrade transaction automatically. However, the simple `cp` to `/data` and then `cp` back to `/data-volume` does not prepare that information in the image correctly, so upon upgrades, weird things might happen.

The solution might be to "revert" that `/data` logic, putting the content back to the image, run the dnf command you need to run, and then regenerate the `/data-template` again with `/usr/local/bin/prepare-volume-template`, putting the symlinks back to the image. Something like
```
RUN cat /etc/volume-data-list /etc/volume-tmp-list | xargs rm -f
RUN cd /data-template && tar cf - . | ( cd / && tar xvf - )
RUN rm -rf /data-template 
RUN ( cd /tmp-template && cp -rp . /tmp ) \
	&& dnf install -y letsencrypt cronie cronie-anacron && dnf clean all
RUN /usr/local/bin/prepare-volume-template /etc/volume-data-list /data
```

**Comment by adelton** [comment]
This will cover new files in directories that already are configured to be stored on the data volume. But how about new directories that the new package store config files and data in which you might want persisted in the data volume, for example `/etc/letsencrypt` or `/var/lib/letsencrypt`?

The solution is to add the new files or directories to the list of paths that should be handled by the persistency logic, before running that `prepare-volume-template`. So something like
```
RUN echo /etc/letsencrypt/ >> /etc/volume-data-list
RUN echo /var/lib/letsencrypt/ >> /etc/volume-data-list
RUN /usr/local/bin/prepare-volume-template /etc/volume-data-list /data
```
will store their content in build time under `/data-template`, make them populated on the data volume upon the first invocation, and the image will just have symlinks to the respective locations under `/data`. (Both those directories are empty but if they had content, the files under them would be stored and populated into the data volume as well.)

**Comment by adelton** [comment]
The miniseries of comments above describes the situation as of today, to get you started.

Do we guarantee that this will always work and will work for any wild extension people decide to make? While we try to be conservative and not break stuff, we cannot give such guarantee unless we know what people expect to work and we have it covered by CI. So if you come up with some working, reasonable, and testable setup, feel free to file a pull request to add it to the Travis CI runs.

**Comment by bpinsard** [comment]
Wow ! Thanks for the super detailed explanation and suggestions! 
I will explore these different options.

**Comment by adelton** [comment]
Let's assume the answers helped to get the work started. If there is something specific needed, let's discuss it in separate and specific issue or pull request.
