### ISSUE TITLE
Clarify usage behind reverse proxy

### ISSUE THREAD

**Issue by ProfessorSalty** [freeipa/freeipa-container#314]
Hello,

I'm hoping to get some clarification here regarding the use of the FreeIPA container behind a reverse proxy, both for myself and to improve the documentation for others. I have a docker setup defined in a compose file and a lot of services sitting behind Traefik 2.2. Owing to FreeIPA's unique requirements, Traefik is routing TCP connections at the path `https://admin.example.com` to the FreeIPA container, port 443. This does let me connect to the front end, but I get an error about the certificates being either self-signed or that the cert has the same serial as an existing cert. From what I can tell in [the documentation](https://www.freeipa.org/page/PKI), I'm able to not generate a cert or generate one that is linked to an existing cert, but it's unclear how I would do this with the containerized server. What I'd like to know:

1) Is there an easier way to place FreeIPA behind a reverse proxy that I haven't seen?
2) What are all the certificates that the container needs in order to run? Would there be an easy way to decouple the certificate generation from the web ui and other components so my proxy can handle SSL termination?
3) If I need to, could I generate the certs from an external source (a [Let's Encrypt](https://github.com/linuxserver/docker-letsencrypt) container, for instance) and then place them in a shared volume? Where would they go?

Thanks for any help

**Comment by adelton** [comment]
In general, I feel that the questions that you pose would better be asked at the FreeIPA users' mailing list (https://lists.fedorahosted.org/archives/list/freeipa-users@lists.fedorahosted.org/) since they do not seem to be specific to FreeIPA containerization.
I assume that you get the error message about self-signed certificates simply because the clients do not have your FreeIPA's CA certificate in their trust setups. You can fix that eigher by adding the CA certificates there, or by using some external CA of your organization -- the FreeIPA container can be bootstrapped with `--external-ca` option, and then started again with the `--external-cert-file` and `--external-cert-file` options once you get the CSR signed by your external CA, just like non-containerized FreeIPA server would.
As for placing FreeIPA server's WebUI behind proxy, there is an writeup of mine about the topic (but again, not specific to containers) at https://www.adelton.com/freeipa/freeipa-behind-ssl-proxy.

**Comment by ProfessorSalty** [comment]
Thanks so much for this!
