### ISSUE TITLE
Refused to install because FQDN not specified when it is

### ISSUE THREAD

**Issue by werdnum** [freeipa/freeipa-container#315]
It looks like the centos-7 container (at any rate) deletes the `/etc/nsswitch.conf` file in the container setup (using [prepare-volume-template](https://github.com/freeipa/freeipa-container/blob/master/utils/prepare-volume-template)), see [here](https://github.com/freeipa/freeipa-container/blob/1b21debaf644393d6eda399a792bf19919831728/Dockerfile.centos-7#L64) and [here](https://github.com/freeipa/freeipa-container/blob/master/volume-data-list).)

Therefore, in the built container, `/etc/nsswitch.conf` is a symlink to `/data/etc/nsswitch.conf` - which is broken on first run until [`populate-volume-from-template`](https://github.com/freeipa/freeipa-container/blob/master/utils/populate-volume-from-template) is called on [line 177 of init-data](https://github.com/freeipa/freeipa-container/blob/1b21debaf644393d6eda399a792bf19919831728/init-data#L177).

However, without `nsswitch.conf`, the system is left with non-functional name resolution (in particular, the `hosts` file is not consulted when `gethostbyname` is called). `hostname -f` calls gethostbyname(gethostname()), and `bash` populates the `$HOSTNAME` environment variable by the same method.

On [line 153 of `init-data`](https://github.com/freeipa/freeipa-container/blob/1b21debaf644393d6eda399a792bf19919831728/init-data#L153), we check if `$HOSTNAME` is a FQDN. But if the FQDN for the current host is in `/etc/hosts`, then this doesn't work because of the lack of functional name resolution!

For those trying to fix this by Google search, this manifested in a few ways:

1. It started with the cryptic "Container invoked without fully-qualified hostname" error caused by the immediate problem.
2. When I ensured that an FQDN was being set and thought the `$HOSTNAME` variable was wrong, I tried to edit `init-data` to set `HOSTNAME=$(hostname -f)` and got "hostname: Name or service not known"
3. I also noticed that logging into the host was super super slow and couldn't figure out why.

FWIW I was running this on a Raspberry Pi 4 running a k3s Kubernetes cluster.

## Recommended fix
Best fix: Don't obliterate files in /etc until after you populate `/data/etc`. All sorts of things break when `/etc/nsswitch.conf` and other files aren't there. So you can populate your `/data-template` directory if you like, but you should leave `/etc` as it is in the image build step, and only replace the files with symlinks once `/data` has been populated.

My guess, by the way, is that this was tested on existing configurations with working `/data` directories, but not brand new installations - so maybe it's worth checking that your CI tests cover this case.

Quick fix: Move the `populate-volume-from-template` call to above the hostname business, and add a `HOSTNAME=$(hostname -f)` line above it.

**Comment by adelton** [comment]
We cannot leave the original content in `/etc` and replace it with symlinks in runtime only after `/data` was populated from `/data-template` because that would be a modification of the image content (not volume content) and that would prevent us from running the containers are read-only. The only other solution I came up with were the (granted, not nice) dangling symlinks.

In the Travis CI setups https://travis-ci.org/freeipa/freeipa-container/branches we run the `tests/run-master-and-replica.sh`'s as configured in https://github.com/freeipa/freeipa-container/blob/master/.travis.yml#L74. All those setups start with empty `/data` directory.

Moving the `populate-volume-from-template` up in `init-data` seems like something that we could do but I need to think some more about the implications.

However, we use `$HOSTNAME` as the hostname source and that seems to work even if `/etc/nsswitch.conf` is not present:

```
$ cat Dockerfile 
FROM registry.centos.org/centos:7
RUN rm /etc/nsswitch.conf
$ docker build -t test-issue-315 .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM registry.centos.org/centos:7
 ---> 3fe89940ae92
Step 2/2 : RUN rm /etc/nsswitch.conf
 ---> Using cache
 ---> 0e33b993129e
Successfully built 0e33b993129e
Successfully tagged test-issue-315:latest
$ docker run --rm test-issue-315 bash -c 'echo $HOSTNAME'
c68f952613dc
$ docker run --rm -h ipa.example.test test-issue-315 bash -c 'echo $HOSTNAME'
ipa.example.test
```
So I'm not quite sure why you see the failures that you see, that we did not hit in the past.

I'm not deeply familiar with what k3s does to handle hostnames. But if it's similar to OpenShift and normal Kubernetes, the control over the fully qualified hostnames is limited there and you might want to just explicitly set the hostname using the `IPA_SERVER_HOSTNAME` environment variable anyway. That's what we do for OpenShift in https://github.com/freeipa/freeipa-container/blob/1b21debaf644393d6eda399a792bf19919831728/freeipa-server-openshift.json#L249

**Comment by werdnum** [comment]
It does seem to be the case that this runs OK in Docker, even when deleting all the files in volume-data-list. So sorry for going off half cocked!

```
➜  test docker build -t test-issue-315 .
Sending build context to Docker daemon  4.608kB
Step 1/3 : FROM centos:7
 ---> 8c52f2d0416f
Step 2/3 : ADD volume-data-list /tmp/volume-data-list
 ---> Using cache
 ---> 9d889017eb03
Step 3/3 : RUN for file in /tmp/volume-data-list; do rm -rf $file; done
 ---> Running in a5a97d8ce4e8
Removing intermediate container a5a97d8ce4e8
 ---> 34930254a8d6
Successfully built 34930254a8d6
Successfully tagged test-issue-315:latest
➜  test docker run --rm test-issue-315 bash -c 'echo $HOSTNAME'
89f2b391050d
➜  test docker run --rm -h ipa.example.test test-issue-315 bash -c 'echo $HOSTNAME'
ipa.example.test
```

Once I get this running (currently working on "`KRB5CCNAME not in environment`" - issue #316), I'll circle back and see if I can figure out a minimal reproduction case.

If it helps, the way it seems to work in Kubernetes is that the only way the hostname can be resolved is because Kubernetes overwrites your `/etc/hosts` with its own version that includes the current host's FQDN. So my guess is that Docker does something different, perhaps using its own DNS server instead of overwriting `/etc/hosts`.

**Comment by adelton** [comment]
Well, no matter what container runtime is used, the hostname should be set via UTS namespace. The `/etc/hosts` might play some role but not in determining what `uname` returns -- that's provided by the kernel.

**Comment by adelton** [comment]
Were you able to minimize this into some reproducer?

**Comment by adelton** [comment]
We seem to have lost traction here.
