### ISSUE TITLE
/var/log/ipareplica-conncheck.log symbolic link missing in latest freeipa-server container

### ISSUE THREAD

**Issue by daniel-milewski-grupawp** [freeipa/freeipa-container#319]
`/var/log/ipareplica-conncheck.log` symbolic link is missing in latest freeipa-server container. This makes `ipa-replica-install` fail when container is run with `--read-only` option. The missing link should point to `/data/var/log/ipareplica-conncheck.log`.

**Comment by adelton** [comment]
You say in latest container -- is that a regression, was it there before?
We do run read-only replica setups in CI, for example https://travis-ci.org/github/freeipa/freeipa-container/jobs/680632592, but it's true that we always run it with `--skip-conncheck` because the typical networking layers in containers made the check pass in the past.
The fix should be adding the path to `volume-data-list`. Can you try if it solves the issue for you?

**Comment by adelton** [comment]
I've added the `/var/log/ipareplica-conncheck.log` to `volume-data-list` and updated tests to run replicas without skipping the connection check in https://github.com/freeipa/freeipa-container/commit/f6a0caa536031315f560b6aeb65e3b15317e635a. The Travis CI test passes: https://travis-ci.org/github/freeipa/freeipa-container/builds/681861051.

Thank you for raising the issue.

**Comment by daniel-milewski-grupawp** [comment]
> You say in latest container -- is that a regression, was it there before?

By "latest" I meant image with ID `50d8e8edd5c3`. I don't know if that was a regression, since it was the first image I've ever tried using. Image with ID `155d255d01d3` (the most up-to-date right now) solved the issue. Thanks!
