### ISSUE TITLE
FreeIPA container repository tags are dangerous for orchestrated production use

### ISSUE THREAD

**Issue by Westie** [freeipa/freeipa-container#343]
See #246

The latest released version has caused issues when updating my installation to the newer version. Why aren't proper tags in use?

**Comment by adelton** [comment]
As noted in https://github.com/freeipa/freeipa-container/issues/246#issuecomment-556998784, there is actually is a fixed tag repository that is browsable athttps://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/rhel7/ipa-server. It is a technology preview container image of IdM for RHEL 7 provided by Red Hat.
As for this upstream FreeIPA containerization effort, the primary reason it was not done (yet) is that there there does not seem to be anyone in the community who would step up and make it happen, not just as a one-time change or proposal but as an ongoing testing and curating process.
We rely on FreeIPA itself being stable and tested in its upstream and in its respective distributions (Fedora, CentOS). If the breakage you experience is caused by the change in FreeIPA itself, you'd experience it on your installations outside of containers as well if you did `dnf update` anyway, so there's not much we could prevent with containers.
You might say that you want to stay on a particular FreeIPA version that is stable for you. Well, if a particular version works for you, tag it specifically in your registries or use SHA to specify a particular image. But note that you will likely not get fixes that way because fixes (including security fixes) will often lead to newer package versions, or fixes (including security) in FreeIPA dependency packages will force upgrade of FreeIPA packages as well.
If the issue you've experienced with new container image seem to be specific to the containerization effort, please report them as issues in this repository so that we can investigate them and hopefully fix them.

**Comment by adelton** [comment]
Having said that, in the past couple of weeks we've changed how container images are built for tests in Travis CI and we've added GitHub Actions as well, so we are currently in fairly good position to be able to push to the Docker Hub or other registry exactly the images that were used for tests, and that could include tagging images with FreeIPA versions or similar. @abbra, would you be in favour of pushing the artifacts images to registries from GitHub Actions, after successful CI runs?
However, whether this will achieve the goal that you @Westie expect is different question.

**Comment by Westie** [comment]
Hi

Thanks for your quick response! I suspect a large part of the issue might be that I wasn't often updating freeipa - and it was only updated as I accidentally deleted the cached copy of the image from the server 😢 

For example, from the update log:

```
2019-02-23T16:06:11Z DEBUG IPA version 4.7.2-1.fc29
2020-09-06T18:08:26Z DEBUG IPA version 4.8.9-2.fc32
```

I had noticed the tag repository mentioned on #246 and #255 however these didn't appear to cover the version that I was running - hence my current tactic of downloading a backup and rescuing the `data` directory and the hash of the image from `/var/lib/docker/image/overlay2/repositories.json`

Being able to tag versions, even if it's on a minor/major level would be especially helpful, I reckon.

**Comment by adelton** [comment]
I don't know, you might want to ask this question on the FreeIPA user mailing list.
But your example demonstrates nicely the problem that I see with your request (and the one in https://github.com/freeipa/freeipa-container/issues/246) -- you've used Fedora-based image for long term operation and you did not even specify the Fedora version for your deployment (or the Fedora 29 installation wouldn't upgrade to Fedora 32). You might want to use CentOS 8 based image for such cases.

**Comment by adelton** [comment]
I guess one thing that we could do would be to remove the `:latest` tag from https://hub.docker.com/r/freeipa/freeipa-server/tags -- that way people would be forced to pick an OS version and there wouldn't be unexpected upgrade from Fedora 29 to 32 like it happened for @Westie.
The drawback to that is that we will get people running Fedora 29 FreeIPA installations for years, without even realizing they run software that is not getting any updates. Because, for each report like https://github.com/freeipa/freeipa-container/issues/246 or this one, there might be dozen of people who had their deployment upgraded to newer versions seamlessly (although I have no data for that claim :-)
Another possibility would be to remove all Fedora images except rawhide from the Docker Hub and just leave CentOS 8 and maybe Fedora rawhide there, to steer people to the CentOS deployments.
@Tiboris, @abbra, what's your opinion?

**Comment by adelton** [comment]
@Westie, I've now checked the version of FreeIPA in `freeipa/freeipa-server:fedora-29` image and it's `freeipa-server-4.7.3-2.fc29.x86_64`. So I assume an easy fix for you was to use `freeipa/freeipa-server:fedora-29` instead of `freeipa/freeipa-server:latest` and the upgrade from 4.7.2-1.fc29 to 4.7.3-2.fc29 would have passed without issues. If that's the case, are the per-Fedora-version tags exactly what you are asking for?

**Comment by adelton** [comment]
I've also now run
```
replica=none tests/run-master-and-replica.sh freeipa/freeipa-server:fedora-29 freeipa/freeipa-server:fedora-32
```
which configures FreeIPA (runs `ipa-server-install`) using the Fedora 29-based image and then uses that data volume with Fedora 32-based FreeIPA server image, running necessary upgrades, and it passed. This test is just a basic "ensure FreeIPA services start up fine" but is shows that things are upgradable across multiple Fedora versions. So if you saw your setup fail after such upgrade, please file issues with the exact problem that you've hit.

**Comment by adelton** [comment]
For the record, the `:latest` tag has been removed from the `docker.io/freeipa/freeipa-server` repository, so folks will have to explicitly chose the OS version they want to use.

(I just hope it does not cause a lot of problems to people who had been using this tag.)

**Comment by adelton** [comment]
In https://github.com/freeipa/freeipa-container/pull/345 I propose adding tags with FreeIPA version to the images pushed to Docker Hub.

However, for production deployment, folks should have a workflow where they deploy images from their registry or other source, not relying on image availability on Docker Hub and upgrading to newer images that have been tested to work for their purposes. Note that Docker Hub now plans to delete images that haven't been pulled for extended periods of time so the older images are bound to disappear unless they are extremely popular and people keep pulling them.
