### ISSUE TITLE
No `latest` tag on hub.docker.com any more

### ISSUE THREAD

**Issue by mvollmer** [freeipa/freeipa-container#346]
As of now, I can `docker pull freeipa/freeipa-server:centos-8` but not `docker pull freeipa/freeipa-server`:

```
docker -v pull freeipa/freeipa-server
Using default tag: latest
Error response from daemon: manifest for freeipa/freeipa-server:latest not found: manifest unknown: manifest unknown
```

**Comment by abbra** [comment]
Yes, this is intentional. Please use explicit versions.

**Comment by abbra** [comment]
See https://github.com/freeipa/freeipa-container/issues/343 for details.

**Comment by mvollmer** [comment]
> Yes, this is intentional. Please use explicit versions.

Ok, which one do you recommend? I have no idea what the practical differences will be for me. 

Please document this.  Dockerhub says:

![image](https://user-images.githubusercontent.com/3228183/93448439-49085d80-f8dc-11ea-8b7c-454a8d35a302.png)

which will not work.

**Comment by martinpitt** [comment]
Would you at least consider getting a ":fedora" tag? We usually want to test against the latest Fedora/FreeIPA to spot regressions, and with a specific Fedora version we'd have to bump the tag rather often (and in practice, will forget about it). The point of containers is that the consumers does not need to care much how it was built, or which underlying OS is inside..

**Comment by abbra** [comment]
There are multiple fedora versions already available -- please use them. For example, you can use fedora-rawhide instead. See all tags here: https://hub.docker.com/r/freeipa/freeipa-server/tags

**Comment by adelton** [comment]
@mvollmer, @martinpitt Thanks for your inputs.

We had couple of issues reported by people who used `:latest` (or just pulled images without the tag and got the default `:latest`) and did not really know or care which version of Fedora or FreeIPA the image uses, until situation when for some reason they repulled the image and got a completely different one and FreeIPA upgraded and sometimes the setup got broken after that upgrade. Their claim was that `:latest` is dangerous for long term production use, even if we've been providing images tagged with the OS versions (`:centos-8`, `:fedora-32`) the whole time so it was possible to limit the deployment at least on OS version level.

We've recently added also tags that show the version of the FreeIPA software in the image (`:centos-8-4.8.4`) so that it's easy to even stay on a particular FreeIPA version. So far we did not get any feedback about usability of that change.

In general I have my doubts about production deployments that rely on pulling images directly from Docker Hub but to minimize the chance of breakage, we've stopped tagging with `:latest`. I understand the pain for the test deployments that the change caused and I've expressed my fear of that happening in https://github.com/freeipa/freeipa-container/issues/343#issuecomment-691120568 -- when testing integration, you don't really care about the FreeIPA version or even Fedora version of the image, you just want some working IPA server.

To help folks in your situation we could likely tag with `:fedora-latest` which would point to the highest released Fedora image (`:fedora-32` at the moment). There's also always `:fedora-rawhide` for the cutting edge and I see @mvollmer mentioned it in https://github.com/cockpit-project/bots/issues/1234#issuecomment-694114408.

Let me know what you think and how to best reconcile those two opposite expectations -- stable for production, and latest for testing.

**Comment by adelton** [comment]
I've now updated the README at https://hub.docker.com/r/freeipa/freeipa-server to talk a bit about tag choices for specific uses.

**Comment by martinpitt** [comment]
Thanks @adelton for the README updates, that's helpful! Indeed we resolved to use the ":fedora-rawhide" tag for testing cockpit upstream -- that's a stable tag name (so we don't forget to update it), and we get the latest version to spot regressions as early as possible.

**Comment by mvollmer** [comment]
> Let me know what you think and how to best reconcile those two opposite expectations -- stable for production, and latest for testing.

I didn't expect to see the base os mentioned so prominently. Looking through the list, I really don't know which one to choose. I want FreeIPA, and I did expect you to choose the best base for it. I did not realize that `:centos-8-4.8.4` contains FreeIPA version 4.8.4 for example.

If there is a choice, it should be about the version and features of FreeIPA itself.

I don't have an opinion about `:latest` per se.
