### ISSUE TITLE
nfs mount on OKD 4.6 results in ls: cannot open directory .: Permission denied

### ISSUE THREAD

**Issue by hend0012** [freeipa/freeipa-container#378]
Issue:

I'm investigating running FreeIPA-container on Openshift, and i got it working without to much issues. The problem i'm facing is as follows:

1 . Create a deployment with a NFS persistent volume (Works)
2. cd into persistent volume mount (Works)
3. Doing anything else will result into ls: cannot open directory .: Permission denied

Cause:

For as far as i can tell, it has something todo with Systemd images, non Systemd images work without any issue. When using a Systemd image, i can't do anything to the persistent volume mount. I also tried the official Centos Systemd image, exact same issue.

Extra info:

I'm running the deployment in privileged mode.

**Comment by abbra** [comment]
This is not specifically an issue with IPA container but a general issue with NFS mountpoints where multiple processes running under different UIDs/GIDs are accessing files on a mount point. If you have no ID mapping enabled on your NFS mounts, NFS client will pass UID/GID numbers to the NFS server and they most likely will be different to what is expected by the server.

Using NFS ID mapping requires Kerberos authentication and a specialized configuration at NFS server side as well. In this case NFS client would transfer user/group names instead of IDs and the mapping will happen at NFS server side. But in order to even 'touch' an NFS mount point, such user needs to be authenticated. With Kerberos authentication, NFS clients needs to find a Kerberos credentials cache to reuse for authentication.

There are multiple issues around this and containers, though. I'd suggest you to look at https://www.reddit.com/r/linuxadmin/comments/l6sil0/need_workaround_for_kerberized_nfs_and/ for some of the investigations done there.

**Comment by hend0012** [comment]
@abbra So why is this only happening with Systemd images, images without Systemd are working fine, UID mappings also seem to do fine

**Comment by abbra** [comment]
This is more about privileged/non-privileged containers. In OKD all systemd containers are privileged, I think. Can you reproduce this on, say, Fedora 33 with unprivileged container? IPA container can run in both privileged and non-privileged modes.

**Comment by hend0012** [comment]
@abbra Yea i can. so the funny thing is, this does not make any difference. Non Systemd image privileged, works(not privileged also works). Systemd image (privileged not working, not privileged also not working).

**Comment by abbra** [comment]
As I said, this is expected -- systemd-based image in OKD is not running under a single host UID, it uses a number of them and most likely is affected by the issues mentioned in that reddit thread.

**Comment by hend0012** [comment]
@abbra OK lets see if this gets resolved, i will close the issue.

**Comment by adelton** [comment]
Does OKD 4.6 already support user namespaces so that systemd does not run as uid 0 on the host and does not require `anyuid`?
