### ISSUE TITLE
Dockerfile Understanding

### ISSUE THREAD

**Issue by guillermocol** [freeipa/freeipa-container#387]
Hello team,

I was about to ask why the Dockerfile of each version (in my case Centos7) is so complex. Is it because running ipa-install-server will not work from the docker container? 
I was just surprised the number of steps that contains the Dockerfile execution.

Thanks,
Guille

**Comment by adelton** [comment]
The layout of the Dockerfiles follows the following pattern:

- enabling reasonably clean run of systemd in the container;
- minimizing the number of services to the ones necessary for FreeIPA execution;
- compatibility needed to have `ipa-server-install` and FreeIPA in general run in container;
- setup needed to have all the configuration and data land in the `/data` volume, for proper persistence;
- configuration to run `ipa-server-install` or `ipa-replica-install` upon the first invocation and configuration needed to handle upgrades between images.

There is a `# test:` line after these sections so that `tests/run-partial-tests.sh` can be used to pinpoint where things break.

The goal obviously isn't to make the Dockerfiles complex without reason. Which step would you propose to eliminate?

**Comment by guillermocol** [comment]
Hello Adelton, I understand thanks for your help. :)
