### ISSUE TITLE
Rocky Linux Container Version

### ISSUE THREAD

**Issue by ashleyprimo** [freeipa/freeipa-container#420]
I am unsure if this is something that would be entertained, at least under this project; but it would be great to have a variant of the RHEL8 container utilising [Rocky Linux](https://hub.docker.com/r/rockylinux/rockylinux) as a base image. 

**Information about Rocky Linux**
[Rocky Linux](https://rockylinux.org/) is a bug-for-bug compatible release of RHEL led by Gregory Kurtzer (founder of CentOS project); Rocky Linux came about due CentOS moving to downstream build model.

**Comment by lui0r** [comment]
Hi,

we run into the same question (not only  for freeipa). EOL for Centos 8:  December 31, 2021. EOL for Centos 7: June 30, 2024. 
At the moment is not yet foreseeable which Alternative will be the right one. Fedora and Centos Live are Upstreams for Redhat, thats def. not what yout want for prod environment. Switching to an alternative is one solution. We decide to switch to debian. I read that freeipa doesn't run on debian due to some bugs. Are there some thoughts to run freeipa in a debian container?

greets

**Comment by ashleyprimo** [comment]
FreeIPA running on Debian (container or otherwise) does not work well in my experience. 

In addition, the FreeIPA Server Debian packages are currently only in the unstable (Sid) repository - https://packages.debian.org/unstable/freeipa-server : last time I tested, I was unable to get it working well on Debian 10 (Buster).

**Comment by abbra** [comment]
Unfortunately, as FreeIPA upstream, we have no real influence on any distributions where we aren't maintainers ourselves. The infrastructure that FreeIPA provides requires substantial maintenance work together with a distribution and if distro maintainers are not interested in that effort, there is very little we can do.

FreeIPA upstream development team does not work on Linux distributions in general. That work is done by the distributions' maintainers, if any. We have few people who share their hats between RHEL and Fedora distribution maintainership, but for Debian and Ubuntu there is a single maintainer who does attempt to keep all packages (~350 something) in a common arrangement so that a basic FreeIPA functionality does work. He is doing that in his available free time and his employer (Canonical) doesn't really invest into that work.

As a FreeIPA upstream team, our focus is primarily in making sure required changes contributed to upstreams of the projects we coordinate as a part of FreeIPA infrastructure: MIT Kerberos, SSSD, Samba, various crypto libraries, browsers, and so on. We would welcome others to help to ensure these updates are part of their preferred distributions, if possible, but that requires someone who actually is interested and willing to commit their own time and effort for this.

So please help distros (Debian et al.) to make sure they are benefiting from FreeIPA infrastructure.

**Comment by adelton** [comment]
I've added `Dockerfile.rocky-8` and `Dockerfile.almalinux-8` to the repository, and the respective `:rocky-8` and `:almalinux-8` images to https://quay.io/repository/freeipa/freeipa-server?tab=tags and https://hub.docker.com/r/freeipa/freeipa-server/tags.

We shall see how sustainable these turn out to be.
