### ISSUE TITLE
Time Sync Error on Docker

### ISSUE THREAD

**Issue by obxjames** [freeipa/freeipa-container#425]
Hi Everyone, 

I have been having trouble with docker container freeipa/freeipa-server:fedora-34-4.9.6 after the question 

`Do you want to configure chrony with NTP server or pool address?`

I have tried yes and no and both I still get an error (still continues the install although) 

`Do you want to configure chrony with NTP server or pool address? [no]: yes
<ime1.google.com,time2.google.com,time3.google.com,time4.google.com
Enter a NTP source pool address, or press Enter to skip: time.google.com

The IPA Master Server will be configured with:
Hostname:       {REDACTED}
IP address(es): 172.17.0.13
Domain name:    {REDACTED}
Realm name:     {REDACTED}

The CA will be configured with:
Subject DN:   CN=Certificate Authority,O={REDACTED}
Subject base: O={REDACTED}
Chaining:     self-signed

NTP server:     time1.google.com
NTP server:     time2.google.com
NTP server:     time3.google.com
NTP server:     time4.google.com
NTP pool:       time.google.com
Continue to configure the system with these values? [no]: yes

The following operations may take some minutes to complete.
Please wait until the prompt is returned.

Disabled p11-kit-proxy
Synchronizing time
Configuration of chrony was changed by installer.
         Starting NTP client/server...
[  OK  ] Started NTP client/server.
Attempting to sync time with chronyc.
[   ***] A start job is running for Configur… first start (1min 55s / no limit)
Process chronyc waitsync failed to sync time!
Unable to sync time with chrony server, assuming the time is in sync. Please check that 123 UDP port is opened, and any time server is on network.
Warning: IPA was unable to sync time with chrony!
Time synchronization is required for IPA to work correctly

Anyone have any advise. I have tried the following

* added --cap-add=SYS_TIME
* added port 123:123/udp
* Checked host and NTP is enabled and `ntpdate -q time.google.com` returns as expected
* Firewall is open to 123 UDP packets

Really not sure what else that could be causing problems. Any ideas?

**Comment by adelton** [comment]
You say

> I have tried yes and no and both I still get an error (still continues the install although)

What error did you get when you answered "no"?

Are you really sure you want to synchronize time from the container, rather than running the time synchronization on the host and use `--no-ntp` in the FreeIPA container?

Using `--cap-add=SYS_TIME` should do the trick. If you still get the "IPA was unable to sync time with chrony", `docker exec` to the container and check journal and `systemctl status chronyd` to see what is reported there.

The issue might also be in the seccomp policy used by the docker deamon. Running `strace` from outside of the container and starting `/usr/sbin/chronyd` in the container might reveal what call no longer succeeds.

**Comment by adelton** [comment]
We seem to have lost traction here.
