### ISSUE TITLE
FreeIPA Security Vulnerabilities

### ISSUE THREAD

**Issue by corang** [freeipa/freeipa-container#434]
Been using FreeIPA as an account management solution for my team and it has worked great. Problem is that we recently started using Tenable.sc to scan our network for vulnerabilities and the FreeIPA container is showing up with a bunch of Critical and High vulns that I don't think can be fixed on my end. If there is some solution please lemme know but otherwise I was hoping that on your end you could at least update the applications mentioned in the attached report. I think it's just apache tomcat being the main offender but I'm not totally sure what else ties into it. Thank you!
[FreeIPA Vulns w_ Desc(1).pdf](https://github.com/freeipa/freeipa-container/files/7621389/FreeIPA.Vulns.w_.Desc.1.pdf)

**Comment by adelton** [comment]
Hello,

you don't specify which container image you used and which version, but since the report talks about tomcat 9.0.30 being installed, I will assume CentOS 8-based image. For CentOS 8, Red Hat's information about RHEL 8's CVEs would be relevant since CentOS mostly just rebuilds RHEL's source packages.

Looking at the first reported Critical issue with CVEs CVE-2019-17569, CVE-2020-1935, and CVE-2020-1938, the matching information is

### https://access.redhat.com/security/cve/CVE-2019-17569

RHEL 8 - pki-deps:10.6/pki-servlet-engine - Not affected - even if the version of the package is 9.0.30, checking the source code reveals that the respective upstream fix https://github.com/apache/tomcat/commit/060ecc5 was applied.

### https://access.redhat.com/security/cve/CVE-2020-1935

RHEL 8 - pki-deps:10.6 and pki-core:10.6 - Fixed via https://access.redhat.com/errata/RHSA-2020:4847

That security errata list numerous packages, the relevant ones would be pki-core-10.9.4-1.module+el8.3.0+8058+d5cd4219 and pki-servlet-engine-9.0.30-1.module+el8.3.0+6730+8f9c6254 and cross checking the packages installed in the container image with
```
$ podman run --rm --entrypoint rpm freeipa/freeipa-server:centos-8 -qa | grep pki- | sort
pki-acme-10.11.2-2.module_el8.5.0+945+a81e57da.noarch
pki-base-10.11.2-2.module_el8.5.0+945+a81e57da.noarch
pki-base-java-10.11.2-2.module_el8.5.0+945+a81e57da.noarch
pki-ca-10.11.2-2.module_el8.5.0+945+a81e57da.noarch
pki-kra-10.11.2-2.module_el8.5.0+945+a81e57da.noarch
pki-server-10.11.2-2.module_el8.5.0+945+a81e57da.noarch
pki-servlet-4.0-api-9.0.30-3.module_el8.5.0+854+e1c92b81.noarch
pki-servlet-engine-9.0.30-3.module_el8.5.0+854+e1c92b81.noarch
pki-symkey-10.11.2-2.module_el8.5.0+945+a81e57da.x86_64
pki-tools-10.11.2-2.module_el8.5.0+945+a81e57da.x86_64
python3-pki-10.11.2-2.module_el8.5.0+945+a81e57da.noarch
```
all of them are of newer version.

### https://access.redhat.com/security/cve/CVE-2020-1938

RHEL 8 - pki-deps:10.6/pki-servlet-engine - moderate with CVSS v3: 6.6 - Affected

The https://access.redhat.com/security/cve/CVE-2020-1938/details=6 has good explanation why Red Hat classified this vulnerability as moderate, differently than NVD and apparently differently than the scanning tool you used, and why therefore that issue was not fixed.

On the example of the first entry in the report I've hopefully shown that throwing scanners at your systems that would just compare the major version numbers of components is bound to produce a lot of false positives that you'd then need to process manually.

To evaluate the vulnerability stance of your deployments and avoid the false positives especially in cases when security fixes are backported to older versions of software, the scanner should use the OVAL information provided by Red Hat, for example https://access.redhat.com/security/data/oval/v2/RHEL8/rhel-8-including-unpatched.oval.xml.bz2.

Hope this helps,

Jan

**Comment by corang** [comment]
@adelton Thanks a ton for this explainer, this makes a lot of sense. Sadly I work in govt and we are mandated to use tenable.sc for security scanning and from what I can tell there's no way to integrate the rhel oval files into the scans. I really appreciate you taking the time to respond though!
