### ISSUE TITLE
cant connect to webui in podman container from outside

### ISSUE THREAD

**Issue by mefisto74** [freeipa/freeipa-container#469]
Hello. i succeffully installed image of freeipa in podman container , had no errors but i cannot browse to webui from browsers, when i type <hostip> in browser this redirect me to ipa.domainname.net and chrome says "ERR_EMPTY_RESPONSE"
network in container in bridge mode with ip 10.89.0.5 , but hosts on my local area network is on 192.168.6.0/24. 
using curl to <hostip> say 192.168.6.100 this give me  this

```
W:\>curl 192.168.6.100
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://ipa.domainname.net/ipa/ui">here</a>.</p>
</body></html>

```

i can successfully resolve ip 10.89.0.5 using 192.168.6.100 bind integradted in freeipa 

```
nslookup ipa.domainname.net 192.168.6.100
╤хЁтхЁ:  UnKnown
Address:  192.168.6.46

╚ь :     ipa.domainname.net
Address:  10.89.0.5
```

ipactl status 

[root@ipa /]# ipactl status
```
Directory Service: RUNNING
krb5kdc Service: RUNNING
kadmin Service: RUNNING
named Service: RUNNING
httpd Service: RUNNING
ipa-custodia Service: RUNNING
pki-tomcatd Service: RUNNING
ipa-otpd Service: RUNNING
ipa-dnskeysyncd Service: RUNNING
ipa: INFO: The ipactl command was successful
```

container was runned using this command 

`podman run -e IPA_SERVER_IP=10.89.0.5 -ti --dns=127.0.0.1 --name rocky-ipa --network newnet  -h ipa.domainname.net -p 53:53/udp -p 53:53 -p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 464:464  -p 88:88/udp -p 464:464/udp -p 123:123/udp -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /var/lib/ipa-data2:/data:Z 2cdf942f6e7f ipa-server-install --setup-dns  --skip-mem-check`

newnet.conflist (network for this container)
```

{
   "cniVersion": "0.4.0",
   "name": "newnet",
   "plugins": [
      {
         "type": "bridge",
         "bridge": "cni-podman1",
         "isGateway": true,
         "ipMasq": true,
         "hairpinMode": true,
         "ipam": {
            "type": "host-local",
            "routes": [
               {
                  "dst": "0.0.0.0/0"
               }
            ],
            "ranges": [
               [
                  {
                     "subnet": "10.89.0.0/24",
                      "rangeStart": "10.89.0.5",
                      "rangeEnd": "10.89.0.5",
                     "gateway": "10.89.0.1"
                  }
               ]
            ]
         },
         "capabilities": {
            "ips": true
         }
      },
      {
         "type": "portmap",
         "capabilities": {
            "portMappings": true
         }
      },
      {
         "type": "firewall",
         "backend": ""
      },
      {
         "type": "tuning"
      }
   ]
}
```

so what am i doing wrong? at least i want to know in whic direction i should investigate. is this dns problem or something? for test i used to used  httpd image from dockerhub 
https://hub.docker.com/_/httpd. used portforwarding like i didn in free ipa and then visited from browser hostip and everything was fine.

upd: if i use curl inside of container this working, but if i use curl on host this say 
curl: (6) Could not resolve host: ipa.domainname.net

if i add to /etc/hosts record 10.89.0.5 ipa.domainname.net
and then curl its also work

so looks like definetely problem with dns but how to fix still dont get it
is this possible to visit web ui in bridge network mode?

upd2
somehow even if i set dns server to freeipa container host i cant go to ipa web ui untill i manually set it record in /etc/hosts. so for me this enough, sorry

**Comment by adelton** [comment]
> upd: if i use curl inside of container this working, but if i use curl on host this say
> `curl: (6) Could not resolve host: ipa.domainname.net`
>
> if i add to `/etc/hosts` record `10.89.0.5 ipa.domainname.net` and then curl its also work
>
> so looks like definetely problem with dns but how to fix still dont get it

You can either keep using the static record in `/etc/hosts`, especially if it's just a testing setup. 

Alternatively you can edit `/etc/resolv.conf` to point to FreeIPA's DNS server ... but you will likely want to make sure that the FreeIPA's DNS server has forwarders correctly configured or you won't be able to resolve other domain.

These two approach will of course make the FreeIPA hostname resolveable only from the machine(s) where you set this up.

If you plan the deployment to be production-level and to use that FreeIPA from whole of your network, you either need the DNS record in your standard `domainname.net` zone in your standard configuration, or if that `domainname.net` is a separate new domain, to be fully managed by FreeIPA, you need delegation to that domain in the parent domain (in this example case in `net`).

That means that instead of that
```
$ nslookup ipa.domainname.net 192.168.6.100
```
when you tell nslookup to talk directly to the FreeIPA's DNS server, you need to get
```
$ nslookup ipa.domainname.net
```
working.

So the whole question really translates to -- how would you get a new DNS record or a zone delegation, in your organization's DNS setup? For that, you should really talk to your network / DNS admins because the exact answer likely depends on many aspects of your organization.

> is this possible to visit web ui in bridge network mode?

Sure, you said that when you have the hostname -> IP address information in `/etc/hosts`, things work. So the problem is the hostname resolution, not the network connection or traffic.

> upd2
> somehow even if i set dns server to freeipa container host i cant go to ipa web ui untill i manually set it record in `/etc/hosts`. so for me this enough, sorry

Where and how did you "set dns server to freeipa container host"?

**Comment by adelton** [comment]
We seem to have lost the traction here.
