### ISSUE TITLE
krb5 keytab not in sync after rejoin

### ISSUE THREAD

**Issue by pasztorl** [freeipa/freeipa-container#476]
Hi,

I've installed freeipa-container as server, then joined some nodes. The auth works. When I run ipa-client-install --uninstall then run the ipa-client-install with the same parameters again as I runned it at first time the accounts are available (id $user works) but auth ( su - $user) fails.
At logs I seen "krb5_child[67874]: Decrypt integrity check failed" messages.

There is a workaround if I update the krb5 keymap by hand using ipa-getkeytab on the client.

Is it a problem with the unenroll (--uninstall)  or the second enroll process, or I miss something?

**Comment by pasztorl** [comment]
Update: the uninstall process also left files under /var/lib/sss/db/ this also can block the auth after rejoin the node.

**Comment by adelton** [comment]
So you have a FreeIPA server container, and you run `ipa-client-install` on some nodes, and the behaviour you observe is strictly on those nodes.

Are those nodes containerized as well, or what environments are they? Do you have an indication that the behaviour you see on those nodes is related to the fact that the FreeIPA server is containerized rather than being a FreeIPA server installation on a RHEL / CentOS / Fedora host?

**Comment by pasztorl** [comment]
Hi adelton,

Now I can reproduce it. If i clean up the /var/lib/sss/db before rejoin the client it works. So I think it is a client side problem and not related the freeipa server.
Yes, the server containerized (big thanks for this project!) with podman. I will try this with k8s container also.
Now, after it successfully working in container I can write k8s operator for manage my nodes. Currently I'm using 3 master.

my client version is 4.8.6

**Comment by adelton** [comment]
If the issues is with the non-containerized clients and not related to the containerized FreeIPA server, there's not really much we can help with here. Please bring the issue to https://lists.fedorahosted.org/archives/list/freeipa-users@lists.fedorahosted.org/ as it seems to be a generic one.
