### ISSUE TITLE
Include maintainer revision in container tagging

### ISSUE THREAD

**Issue by remil1000** [freeipa/freeipa-container#478]
Greetings,

first of all thanks for the hard work pushing FreeIPA inside a container and making
it work quite seemlessly in such an environment.

Also thank you for providing an appropriate versioning/tagging which provides
hints on the underlying system and FreeIPA version shipped in the container.

Small request tough, could you include a maintainer revision in this version ?
for example `fedora-36-4.9.10-1`, `fedora-36-4.9.10-2`, and so on

I've noticed on the 6th of September 2022 the fedora-36-4.9.10 tag has been
overwritten in the Docker Hub

Until 6th of September fedora-36-4.9.10 was f952df5a37d5
`freeipa/freeipa-server   fedora-36-4.9.10   f952df5a37d5`

On the 6th the same tag points to ab979c63ed0f
`freeipa/freeipa-server   fedora-36-4.9.10   ab979c63ed0f`

And while writing this it is now is pointing to 259ffecac077
`freeipa/freeipa-server   fedora-36-4.9.10   259ffecac077`

This to avoid any surprise when redeploying a system with a version users would
think is fixed and also to ease version identification for issue/bug tracking
as it would be confusing that a setup with the same docker tag may exhibit
different behaviour/bug

As the `build-id` is regenerated this also triggers a useless upgrade attempt
of FreeIPA

```
/data/build-id /data-template/build-id differ: byte 1, line 1
FreeIPA server is already configured but with different version, starting upgrade.
```

Thanks a lot

**Comment by adelton** [comment]
So you ask for each new image respin to get a new maintainer revision?

We are rerunning the CI three times per week. Since last week thanks to https://github.com/freeipa/freeipa-container/commit/4a1beb82bb5285295c316d308080f22acd48b0e2 we minimize the churn in the repositories by not pushing the images if the base image, the set of rpms, and the content that goes to the image from this repository did not change, but you can still see the images getting updated very frequently because one of the hundreds of dependent packages might have gotten updated at any moment, especially in Fedora. And you want the latest updates because they (typically) fix security and functionality bugs. So the updates of the images on the Docker Hub are expected and a good thing.

If you care about the image staying the same for your deployment purposes, my recommendation is to just tag an image that passed your QA/stage testing in your namespace, either in the public repository like Docker Hub or Quay or in your internal repository. You should select image based on functional suitability for your purposes, after testing it, and retest and deploy new versions continually --- not based on the fact that on the day of the initial deployment
```
freeipa/freeipa-server fedora-36-4.9.10 f952df5a37d5
```
was the last image, and you'd be stuck with that image for years to come, having potentially insecure setup because you won't get the updates.

And if you do not plan to do some stage testing before deploying the initial image, why do you care that it gets updated (giving you the latest released fixes)?

By the way, if you want the latest fixes but also want slow pace of updates, maybe Fedora-based image is not what you really want -- CentOS 9 Stream might be more suitable. I also plan to add Rocky Linux 9 and AlmaLinux 9 images in the near future to provide even more stable images (in terms of cadence of changes and the QE that the software has undergone before release).

If the identification of the image for reporting purposes is what you are after, we recently also added https://github.com/freeipa/freeipa-container/commit/f97705bd967ce6b413461dc18f7c8fb89428a38c and https://github.com/freeipa/freeipa-container/commit/0baa11cf452523dbb610b6c79e974725d711f496 so the `org.opencontainers.image.*` labels should provide all the relevant information you need, including links to CI jobs that actually built the image (once images are rebuilt with this logic included). That in turns shows the exact rpm versions-releases of all packages in the log.

But also note that if you hit a problem, outside of containers, the first question likely will be "is the problem still present with the latest updates applied"? In the containerized setups, the equivalent will be "can you retry with the latest `freeipa/freeipa-server:fedora-36` image?".

Or when you talk about `4.9.10-1`, `4.9.10-2`, do you have the actualy rpm release of the `freeipa-server` packages in mind? But that's just one of hundreds of packages on the image -- why should that package block respin of the image with potentially security fixes of the dependent packages?

**Comment by remil1000** [comment]
That's about the point, noticing when there is a version bump because of security or other fix.
That's about the same as the underlying RPM packages you're using, no upstream maintainer would release new packages without a version bump or you would need to keep a rpm-mirror/satellite on the side which, obviously, few people are doing. 

Seeing the work already done in the container metadata I guess this was already a concern before.
I'll just keep a copy of the freeipa container on a separate registry, it'll only be a minor annoyance

**Comment by adelton** [comment]
The difference between rpm's NVR's and container images as I see it is that container images explicitly use the content-based addressing (the digest, and/or the image id, those f952df5a37d5,  ab979c63ed0f,  259ffecac077) as part of all workflows.

The work I did to avoie pushing images unnecessarily was done primarily to minimize the load we put on the registries (that we get to use as a distribution mechanism for free). Tagging each new image release with separate tag would reverse that effort because the images would need to be held by the registries indefinitely.
