### ISSUE TITLE
Some DNS entries not changed in `update_server_ip_address`

### ISSUE THREAD

**Issue by ikogan** [freeipa/freeipa-container#51]
Perhaps I'm not understanding the way `update_server_ip_address` is supposed to be used but it seems like there are two things that aren't updated when the IP address is set, `ipa-ca.$(hostname -d)` and the reverse zone. It's fairly easy to update those using `ipa` like this:

``` sh
OLD_IP_ADDRESS=$(ip addr show | awk '/inet .*global/ { split($2,a,"/"); print a[1]; }' | head -1)

kdestroy -A
echo "${ADMIN_PASSWORD}" | kinit admin
ipa dnszone-del $(echo ${IP_ADDRESS} | awk -F. '{ print $3"."$2"."$1 }').in-addr.arpa
ipa dnszone-add $(echo ${NEW_IP_ADDRESS} | awk -F. '{ print $3"."$2"."$1 }').in-addr.arpa --name-server=$(hostname -f). --admin-email=hostmaster.$(hostname -d). --allow-sync-ptr=1 --dynamic-update=1
ipa dnsrecord-mod $(hostname -d) $(hostname -a) --a-rec=${OLD_IP_ADDRESS} --a-ip-address=${IP_ADDRESS}
ipa dnsrecord-mod $(hostname -d) ipa-ca --a-rec=${OLD_IP_ADDRESS} --a-ip-address=${IP_ADDRESS}
kdestroy -A
```

The issue I'm having is being reliably able to determine the admin password on startup. I'd prefer not to have to store it in a file (actually, why is the ds master stored in a file?), but the system keytab isn't enough to update those records. Would it be useful to alter the ACLs so it can? Is there a reason `nsupdate` is used currently rather than `ipa` besides the above issue? Is there a reason those aren't updated?

**Comment by adelton** [comment]
The ```update_server_ip_address``` is really a quick bandaid to make the IPA server discoverable / resolvable by clients and by itself alike. There are many related issues in attempting to do it completely and fully -- for example, when the FreeIPA server is a DNS server for its domain, glue records in parent domain likely also need to be modified, and that zone can be completely out of reach of the FreeIPA server.

I've filed https://fedorahosted.org/freeipa/ticket/5629 to get the utility added to FreeIPA itself and have it supported. However, it might be hard to do and in general, people seem to prefer that the orchestration layer does the work (because it might have better chance of updating the parent zones as well, for example).

As for your proposed code -- the problem with using ```ipa``` (as opposed to ```nsupdate```) is that it likely will not work when external DNS server is used.

I also don't think we want to just freely create new (reverze) zones. We can try to update the PTR when the reverze zone already exists. The note about ```ipa-ca``` is correct but the IPA server might not be a CA so it needs to be wrapped by some checks. I feel having it a CNAME might be better approach long term.

I'll get back to this issue and try to do at least some of the improvements that you suggest.

**Comment by adelton** [comment]
> why is the ds master stored in a file?

Looking at the git history, it was used by ```ipa-ldap-updater```. I need to check if it's still needed in the latest versions.

**Comment by adelton** [comment]
> I feel having it a CNAME might be better approach long term.

It looks like there was a good reason to move away from CNAME, to be able to store list of all CAs: https://fedorahosted.org/freeipa/ticket/3547. So this idea will not fly.

**Comment by ikogan** [comment]
Is it safe to use `ipa` if we can tell that the current server is authoritative on the domain? While that'll likely fail to update parent servers, will it at least reliably update the current server?

**Comment by adelton** [comment]
> > why is the ds master stored in a file?
> 
> Looking at the git history, it was used by ipa-ldap-updater. I need to check if it's still needed in the latest versions.

It was removed in 40baa2f1a0eb4b6eb49ec3255ebf507578210c4c.

**Comment by adelton** [comment]
There is another problem with updating more than machine's own IP address -- authorization. Your example code shows

`
echo "${ADMIN_PASSWORD}" | kinit admin
`

but in general case we cannot expect to have admin's password available to be able to authenticate as admin.

And `host/ipa.example.test` principal is only allowed to update its own DNS record, not `ipa-ca`.

**Comment by ikogan** [comment]
Thanks for the updates. Is it still possible to use `nsupdate` for this then?

**Comment by adelton** [comment]
Yes for `ipa.example.test` (the canonical record). Not for `ipa-ca.example.test`.

**Comment by adelton** [comment]
Is there anything else in this issues which needs to be addressed/investigated?

**Comment by felipevolpone** [comment]
Closing this due lack of activity.
