### ISSUE TITLE
please add EPN tool 

### ISSUE THREAD

**Issue by hillar** [freeipa/freeipa-container#527]
please add [ Expiring Password Notification (EPN) tool ](https://github.com/freeipa/freeipa/blob/master/ipaclient/install/ipa_epn.py)

**Comment by adelton** [comment]
It is already in the images, see for example:
```
$ podman run --rm -ti --entrypoint rpm quay.io/freeipa/freeipa-server:fedora-38 -ql python3-ipaclient | grep ipa_epn.py
/usr/lib/python3.11/site-packages/ipaclient/install/ipa_epn.py
```

**Comment by hillar** [comment]
yeah, sorry just found it ;/

so as i understand only thin i am missing is https://github.com/freeipa/freeipa/blob/master/client/ipa-epn.in

**Comment by abbra** [comment]
@adelton it is `freeipa-client-epn`.

**Comment by adelton** [comment]
Well, I was searching for
```
$ podman run --rm -ti registry.fedoraproject.org/fedora:38 dnf whatprovides '*/ipa-epn.in'
Fedora 38 - x86_64                              7.7 MB/s |  83 MB     00:10    
Fedora 38 openh264 (From Cisco) - x86_64        2.2 kB/s | 2.5 kB     00:01    
Fedora Modular 38 - x86_64                      1.9 MB/s | 2.8 MB     00:01    
Fedora 38 - x86_64 - Updates                    4.4 MB/s |  12 MB     00:02    
Fedora Modular 38 - x86_64 - Updates            632  B/s | 257  B     00:00    
Error: No matches found. If searching for a file, try specifying the full path or using a wildcard prefix ("*/") at the beginning.
```
:-)

I wonder what the functional expectation would be here and if this should indeed be part of the freeipa-server container, rather than being in a separate container. The name of the package having client in it suggests that this might be meant to be decoupled from the server.

From the technical point of view, the `/etc/ipa/` is already a symlink to `/data/etc/ipa/` in the freeipa-server container, so configuring `epn.conf` should work, and so should enabling the timer in `/data/etc/systemd/system/`.

**Comment by adelton** [comment]
@hillar @abbra Any opinion about including it in the FreeIPA server container image vs. having it in a separate (client) container?

**Comment by abbra** [comment]
@adelton If you have that separate container, then add there. If not, adding it to IPA server container probably wouldn't hurt much.

**Comment by adelton** [comment]
Makes sense. Thanks, added to master and to images based on recent OS versions.
