### ISSUE TITLE
How to make docker host enroll as ipa client ?

### ISSUE THREAD

**Issue by sergpolly** [freeipa/freeipa-container#539]
Hello,

We are a small research lab running few compute servers and a NAS. NAS is running a containerized freeipa server instance. It works great ! - compute nodes are enrolled into IPA-realm using ipa-client on bare metal (OS is ubuntu 20.04 everywhere).
However, I have troubles dealing with our NFS-shares from our NAS - mostly related to user permissions and such. It would be much easier if I could enroll host-OS on our NAS into the same IPA-realm - i.e. let the NFS-server be aware of  users and groups - _**is it possible to do it somehow ?**_
Naive approach (ipa-client on host OS) doesn't work because hostname is already used by the dockerized IPA-server ...
We could use another small server just to run IPA-server, but then what is the point of containerization ...
We would appreciate any insight/suggestion into how to improve our setup or ideas on how to make host-OS aware of IPA-users

Thank you so much !

Here is how I run our IPA-server on the NAS server:
```sh
IP=NAS_server_IP
docker run -d --name ipa \
    -h ipa.dekkerlab.org \
    --add-host ipa.dekkerlab.org:${IP} \
    -p 80:80 \
    -p 443:443 \
    -p 389:389 \
    -p 636:636 \
    -p 88:88 \
    -p 464:464 \
    -p 88:88/udp \
    -p 464:464/udp \
    --read-only \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    -v /var/lib/ipa-data:/data:Z \
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
    freeipa/freeipa-server:rocky-9 -U --no-ntp --ip-address=${IP} \
        -n dekkerlab.org -r DEKKERLAB.ORG -p $PASSWD1 -a $PASSWD2
# just in case - ipa2 replica - seems to wor4k
#--add-host ipa2.dekkerlab.org:146.189.160.174 \
```

I could not figure out the DNS server part, so I'm just specifying my servers in the `/et/hosts` like so:
on the NAS:
```sh
127.0.0.1	localhost
# purgatory
172.26.38.40	purgatory.dekkerlab.org	purgatory
# limbo
172.26.38.41	limbo.dekkerlab.org	limbo
# abyss NAS
172.26.38.42	ipa.dekkerlab.org	ipa
```
on compute nodes:
```sh
127.0.0.1	localhost
127.0.1.1	purgatory	
# purgatory
172.26.38.40	purgatory.dekkerlab.org	purgatory
# limbo
172.26.38.41	limbo.dekkerlab.org	limbo
# abyss NAS
172.26.38.42	ipa.dekkerlab.org	ipa

```

**Comment by sergpolly** [comment]
Thank you for a quick reply !
I didn't know this was possible ... My understanding of networking and containers is very shallow ...

Do I understand correctly - that according to your suggestion my setup should look as:
```bash
IP=172.26.38.42
docker run -d --name ipa \
    # hostname of the container running IPA-server not visible/reachable outside of the container
    -h host1.dekkerlab.org \
    # hostname of the host-OS
    --add-host ipa.dekkerlab.org:${IP} \
   # unchanged below ...
```
and then I should keep using `ipa.dekkerlab.org` as an IPA-server for enrolling clients (including `ipa.dekkerlab.org` itself ) ?

**Comment by adelton** [comment]
Well, I thought it would be the other way round -- the IPA server in the container named `ipa.dekkerlab.org`, the host (which is also the NAS and NFS server?) named `host1.dekkerlab.org`. But the actual names do not really matter.

I'm not sure I understand the `--add-host ipa.dekkerlab.org:${IP}` -- that just helps the IPA server resolve the IPA client (== host on which the container runs) ... but why does it need to do that?

For the planning purposes and understanding the network layout, it might actually help you to think of the IPA server as a separate host, or a VM on that NAS server. Think of the naming, of the IP addresses, etc. And then you just make a mental switch and say "instead of a VM", it is a container. And you either give the IPA server the same IP address as the NAS server, or (I assume) you can give the NAS server second IP address to make even externally the two (the NAS server providing NFS services, and the IPA server running there in the container) distinguished.

You also say

> I could not figure out the DNS server part, so I'm just specifying my servers in the /etc/hosts

Using `/etc/hosts` works for testing but if you then add another IPA client, you would need to propagate the values to its `/etc/hosts` as well. Do you have a DNS server (outside of that IPA server)? Why doesn't adding the A records work? Overall, anything general should be in the DNS server, and only local "overrides" should go to `/etc/hosts`. For example, on the host hosting the IPA server container, you might want to have a `/etc/hosts` entry to specify the IP address of the container in question so that the client processes go to the container directly, rather than going through the public IP address of the host (and via the port mapping to the container).

**Comment by adelton** [comment]
By the way, if you are not running DNS server in the IPA server (you do not use `--setup-dns`), the `--ip-address=${IP}` is likely not needed either. Without it, the processes within the container will use whatever the internal IP address is, and for the external processes (on the NAS server, and the other clients), the DNS records, or worst case `/etc/hosts` is what matters.

**Comment by sergpolly** [comment]
Thank you so much @adelton !
just as you've suggested, I got my IPA "config" down to:
```bash
docker run -d --name ipa \
    -h ipa.dekkerlab.org \
    -p 80:80 -p 443:443 -p 389:389 -p 636:636 -p 88:88 -p 464:464 -p 88:88/udp -p 464:464/udp \
    --read-only \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    -v /var/lib/ipa-data:/data:Z \
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
    freeipa/freeipa-server:rocky-9 -U --no-ntp \
       -n dekkerlab.org -r DEKKERLAB.ORG \
       -p PWD1 -a PWD2
```
and configured `/etc/hosts` on our NAS as:
```bash
# clients entries ...
# abyss NAS 
172.26.38.42	abyss.dekkerlab.org	abyss
# IPA server on the NAS - get the IP from "docker inspect ipa" !
172.34.0.2	ipa.dekkerlab.org	ipa
```
while other clients still have it as:
```bash
...
# IPA server running on the NAS - use NAS's actual IP
172.26.38.42	ipa.dekkerlab.org	ipa
```
so, indeed: 
>  And then you just make a mental switch and say "instead of a VM", it is a container located on a specific machine

this was the hardest thing to realize ... I didn't understand how a VM/docker and a host could have different IPs - for external clients i mean ... this would imply at the very least getting another IP address from our IT ... But anyways - I think the trick with the internal docker IP address, as you've suggested, worked well - i.e. NAS belongs to 2 networks docker one and "real" one, while docker-freeIPA translates itself to the "world" using NAS's IP ... - neat ! Now my NAS is aware of IPA users ! Thanks a lot !

As far as DNS is concerned - my main problem is that I don't know it ... never configured it before, and after trying a couple of times with freeIPA I just gave up ... I hope it should be possible to upgrade  the existing container to include DNS-service while keeping all of the user/group-entries intact.

PS. those unnecessary options I've used, such as `--add-host ipa.dekkerlab.org:${IP}` and such are just a byproduct of shallow understanding ... But today I improved a bit ! Thank you so much !

**Comment by zwets** [comment]
> > Naive approach (ipa-client on host OS) doesn't work because hostname is already used by the dockerized IPA-server ...
> Is there any reason why the hostname of the IPA server (what you specify with `docker run -h ...`) needs to be the same as the hostname of the host where that IPA server is running?

@adelton apologies for hijacking this thread for this question, but the answer is probably simple: _should_ the container have its own hostname (& IP)?

I have set up FreeIPA on two small installations (thank you so much for the solidity of this solution!). On the first the containers run as if they were separate hosts (with their own host name and IP). On the second, they run "through" their hosts, i.e. their hosts double as compute nodes in the cluster *and* IPA server and replica.

The first definitely "feels cleaner", but needed quite some juggling with Docker network definitions and the UFW firewall. 

The second also works, but I'm wondering if it won't run into trouble because the "inside view" from the container is different from the outside view. E.g. there are two versions of the IPA host's keytab: the one inside the container and the one on the host.

Would you recommend the one over the other setup?

**Comment by adelton** [comment]
Conceptually the criterion I'd look for is whether the host is a machine dedicated only to running the IPA server and nothing else.

For example, if you have a VM with an OS for which FreeIPA is not available (built) natively and you just want to dedicate that host to FreeIPA, using the same hostname likely works, and you could likely also use the same krb5.keytab both in the container and on the host because even from the access control point of view they are "the same" -- the processes just run in some namespaces and under some additional layers of isolation. And when you decide you need to move the FeeIPA server to a different physical machine, you just move the whole VM.

When the host is a more generic-purpose one and among other services it just happens to also run the FreeIPA container (like the NAS discussed in this issue), then it makes sense to think of that FreeIPA container as a separate machine, with identity distinct from that of the host. Today it runs on this host under docker, tomorrow you might move it to different host under podman, next week you will move it to a Kubernetes cluster. The FreeIPA server hostname stays the same, the IP address might even stay the same, and you will be able to treat the machines running that container as separate IPA clients.

Or maybe think of this: you start with your first FreeIPA master `ipa1.example.com`, in two months time you create three more replicas `ipa2.example.com` through `ipa4.example.com` and you decide to remove that initial master. Will you remove the whole host, or just the container? If you remove just the container but the host continues to serve other purpose, will you want to have that host named `ipa1.example.com` still around?

I would lean towards having separate identities for the FreeIPA server container and for its host in spite of slightly more planning and configuration needed around its network setup, unless there is an indication that the flexibility that this gives you will never be needed.
