### ISSUE TITLE
Delete files under var/log

### ISSUE THREAD

**Issue by JoyceBabu** [freeipa/freeipa-container#542]
I am moving a FreeIPA server to a new docker host. There are a few GBs of log files under `/data/var/log`.

Is it safe to delete all files under `/data/var/log/` ?

**Comment by rcritten** [comment]
You probably need to keep the directory structure at a minimum but it should be fine to remove the files. I can't say I've done it though.

But that said...

The logs represent the activities that have happened. I would retain them myself otherwise you'll have no visibility into what changes have been made by whom.

IMHO there is important history contained there.

**Comment by JoyceBabu** [comment]
Thank you. I will keep the logs.

**Comment by adelton** [comment]
Keeping them gzipped as part of the migration backup might be just fine though -- I sincerely hope FreeIPA does not need them around for any subsequent functionality.

**Comment by rcritten** [comment]
They aren't necessary for operation, but if you wonder at some point "Who deleted Jan's account" without the logs you'd have no idea without them. I just think that as a deployment having active logging is a good idea.
