### ISSUE TITLE
ipa-restore does not work

### ISSUE THREAD

**Issue by jamuir** [freeipa/freeipa-container#543]
Thank-you for making freeipa-container available.  Unfortunately, `ipa-restore` does not work.

*steps to reproduce:*

1. login to a previously configured container
2. create a backup using `ipa-backup`
3. attempt to restore from that backup using `ipa-restore <dirname>`

Here is the output I get for step 3:

```
[root@670941dca03e /]# ipa-restore ipa-full-2023-06-29-15-01-21
Directory Manager (existing master) password: 

Preparing restore from /var/lib/ipa/backup/ipa-full-2023-06-29-15-01-21 on ldap.crypto4a.lan
Performing FULL restore from FULL backup
Temporary setting umask to 022
Restoring data will overwrite existing live data. Continue to restore? [no]: yes
Each master will individually need to be re-initialized or
re-created from this one. The replication agreements on
masters running IPA 3.1 or earlier will need to be manually
re-enabled. See the man page for details.
Disabling all replication.
Stopping IPA services
Systemwide CA database updated.
Restoring files
Restoring files failed: tar: etc/resolv.conf: Cannot open: File exists
tar: var/lib/ipa/gssproxy/http.keytab: Cannot open: Not a directory
tar: var/lib/ipa/certs/httpd.crt: Cannot open: Not a directory
tar: var/lib/ipa/private/httpd.key: Cannot open: Not a directory
tar: var/lib/ipa/ra-agent.pem: Cannot open: Not a directory
tar: var/lib/ipa/ra-agent.key: Cannot open: Not a directory
tar: etc/hosts: Cannot open: File exists
tar: Exiting with failure status due to previous errors

Systemwide CA database updated.
Restoring from userRoot in CRYPTO4A-LAN
Restoring from ipaca in CRYPTO4A-LAN
Restarting GSS-proxy
Starting IPA services
Restoring umask to 18
CalledProcessError(Command ['/usr/sbin/ipactl', 'start'] returned non-zero exit status 1: 'Failed to start httpd Service\nShutting down\nHint: You can use --ignore-service-failure option for forced start in case that a non-critical service failed\nAborting ipactl\n')
The ipa-restore command failed. See /data/var/log/iparestore.log for more information
[root@670941dca03e /]#
```

Unfortunately, the failed restore operation breaks httpd:

```
[root@670941dca03e /]# ipactl --ignore-service-failures start
Existing service file detected!
Assuming stale, cleaning and proceeding
Starting Directory Service
Starting krb5kdc Service
Starting kadmin Service
Starting httpd Service
Failed to start httpd Service
Forced start, ignoring httpd Service, continuing normal operation
Starting ipa-custodia Service
Starting pki-tomcatd Service
Starting ipa-otpd Service
ipa: INFO: The ipactl command was successful
```
Version info:

```
[root@670941dca03e /]# ipa --version
VERSION: 4.10.1, API_VERSION: 2.251
```

**Comment by jamuir** [comment]
Maybe the issue is that the restore process does not expect `/var/lib/ipa` to be a symlink.

```
[root@d6adbf31e101 /]# ls -l /var/lib/ipa
lrwxrwxrwx 1 root root 17 Jun 14 00:30 /var/lib/ipa -> /data/var/lib/ipa
```

**Comment by adelton** [comment]
That is possible. We'll need to compare the backups generated by `ipa-backup` in the container to those from on-host FreeIPA installations, to figure out if the backups itself are even complete (due to the symlinks where `ipa-backup` does not expect them).

It might take me a couple of weeks to get to it so if anyone is able to start with the analysis, that might help.

**Comment by adelton** [comment]
What OS / image was the container run from exactly? I added the `ipa-backup`, `ipa-restore`, and `ipactl start` commands to a test CI run https://github.com/adelton/freeipa-container/actions/runs/5552223340/jobs/10139458906 and it passed on all OSes ...

**Comment by adelton** [comment]
The more I was thinking about this, the more I'm getting to the conclusion that the usefulness of the `ipa-backup` / `ipa-restore` in the container is limited. Together with the issues caused by the fact that some locations have symlinks where the tooling expects files, the backup will likely be broken anyway, even if the backup + restore don't report any error.

So I'm leaning towards just documenting in the README that `ipa-backup` / `ipa-restore` should not be used, that to backup the container, it should be stopped and the content of the volume directory mounted to `/data` backed up on the host.

Does that sound reasonable?

We could potentially also remove the `ipa-backup` and `ipa-restore` from the container images altogether, so that people are not inclined to rely on them. But that might be too harsh for people who like to dig under the hood of things and have a specific use-case in mind.

**Comment by jamuir** [comment]
> to backup the container, it should be stopped and the content of the volume directory mounted to /data backed up on the host.

That sounds reasonable.  In fact, making a copy of the container volume `/data` was the first method I tried when I wanted to create a back-up.  Unfortunately, I had problems restoring from that back-up.

I was trying to move the data from one machine to another and I believe I ran into mismatched uid/guid ranges.

Keeping the data on the same machine did work (i.e. creating a new container on the same machine using `/data` from the original container).

**Comment by adelton** [comment]
> I was trying to move the data from one machine to another and I believe I ran into mismatched uid/guid ranges.

Was this related to rootless container / running with user name spaces and supplementary uids/gids in `/etc/subuid` and `/etc/subgid` being different? Or something else?

**Comment by jamuir** [comment]
Yes, that was it.

When I moved the data to the new machine, the account I used had different ranges inside `/etc/subuid` and `/etc/subgid` and so the imported `/data` volume was not compatible.

**Comment by adelton** [comment]
Thanks for the confirmation. I've now created https://github.com/freeipa/freeipa-container#backup-and-restore section in README, via 9e4d8cd133cae19afdbc998fd5003f7c69fd25ee.
