### ISSUE TITLE
Info on Docker environment variables

### ISSUE THREAD

**Issue by mlazzarotto** [freeipa/freeipa-container#592]
Good morning,
it seems to me that the documentation in the **README.md** is not particularly extensive, and especially I notice that there is no section with all the available environment variables to use with Docker.
Am I looking in maybe the wrong place?

**Comment by adelton** [comment]
Which environment variable do you find missing?

**Comment by mlazzarotto** [comment]
Hi, there's not a particular environment variable that I can't find, but I was wondering if there's somewhere a list of all the available variables.

**Comment by adelton** [comment]
Not really. Note that the `docker run` (`podman run`, docker-compose YAML, K8s YAML) parameters, as well as parameter to the container invocation that get passed to `ipa-server-install`, are much more crucial than the environment variables.

But checking https://github.com/freeipa/freeipa-container/blob/master/init-data we have

- `PASSWORD`

which is just a shortcut for specifying the password in the `ipa-server-install` argument list,

- `IPA_SERVER_INSTALL_OPTS`

which is an alternative way to specifying the `ipa-server-install` argument list,

- `IPA_SERVER_HOSTNAME`

which you don't need with `docker run` where you can use `-h`,

- `IPA_SERVER_IP`

which in latest versions of FreeIPA is not really needed because `--ip-address` seems to work,

- `DEBUG_NO_EXIT`

which is an equivalent to `no-exit` container parameter, and lastly

- `DEBUG_TRACE`

which just does `set -x` for the initial `init-data` setup script.
