### ISSUE TITLE
arm64 images

### ISSUE THREAD

**Issue by fichte** [freeipa/freeipa-container#596]
Hi,

is there any problem to provide arm64 images? I successfully built the rawhide image for arm64. It would be nice if they could be provided as the amd64 images.

Thank you
fichte

**Comment by adelton** [comment]
The problem is to do it in a sustainable way with some guarantees of functionality and updates (respins) of those image, not just do a one-off build and then let it rot. The convenience of having built arm64 images for users is also a liability for this project, something I don't treat lightly given fairly limited number of maintainers and the time they can devote to the project. Even getting and keeping the existing matrix of images (all on x86_64) working is nontrivial, for example we currently don't test and push Fedora rawhide and CentOS 9 Stream images due to https://bugzilla.redhat.com/show_bug.cgi?id=2265995 and https://issues.redhat.com/browse/RHEL-20465. Add another architecture to the mix and the maintenance complexity might multiply.

(Which, by the way, means that while you might have built a Fedora rawhide image -- does it work? It fails for me: https://github.com/adelton/freeipa-container/actions/runs/8234965268/job/22518208838)

Currently we build the images for https://quay.io/repository/freeipa/freeipa-server?tab=tags and https://hub.docker.com/r/freeipa/freeipa-server/tags using GitHub Actions' hosted runners which are x86_64 (amd64). For arm64 builds we could either do multi-arch builds with `docker buildx` on those x86_64 runners but then couldn't test them there; or we could builds on Cirrus CI or CircleCI but even if we got the systemd-in-container running on those CIs to run the tests, we'd then have the problem of integrating those two completely separate sources of images into single manifest for reasonable consumption.

Neither of those approaches screams easy. Are there any others?

I tested building with Cirrus CI and CircleCI before but on neither platform did I get stable setup to even run the CI jobs (without pushing the built images to Quay/Docker Hub).

That's why I'm currently waiting to see if the ARM-runners of GitHub Actions mentioned in https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/ will become available outside of the private beta and what they will look like, to give our ARM options another look.

**Comment by fichte** [comment]
> The problem is to do it in a sustainable way with some guarantees of functionality and updates (respins) of those image, not just do a one-off build and then let it rot. The convenience of having built arm64 images for users is also a liability for this project, something I don't treat lightly given fairly limited number of maintainers and the time they can devote to the project. Even getting and keeping the existing matrix of images (all on x86_64) working is nontrivial, for example we currently don't test and push Fedora rawhide and CentOS 9 Stream images due to https://bugzilla.redhat.com/show_bug.cgi?id=2265995 and https://issues.redhat.com/browse/RHEL-20465. Add another architecture to the mix and the maintenance complexity might multiply.
> 
> (Which, by the way, means that while you might have built a Fedora rawhide image -- does it work? It fails for me: https://github.com/adelton/freeipa-container/actions/runs/8234965268/job/22518208838)

i created a pull request which fixes this /etc/pki/pki-tomcat issue see https://github.com/freeipa/freeipa-container/pull/597

> 
> Currently we build the images for https://quay.io/repository/freeipa/freeipa-server?tab=tags and https://hub.docker.com/r/freeipa/freeipa-server/tags using GitHub Actions' hosted runners which are x86_64 (amd64). For arm64 builds we could either do multi-arch builds with `docker buildx` on those x86_64 runners but then couldn't test them there; or we could build on ARM on Cirrus CI or CircleCI but even if we got the systemd-in-container running on those CIs to run the tests, we'd then have the problem of integrating those two completely separate sources of images into single manifest for reasonable consumption.
> 
> Neither of those approaches screams easy. Are there any others?
> 
> I tested building with Cirrus CI and CircleCI before but on neither platform did I get stable setup to even run the CI jobs (without pushing the built images to Quay/Docker Hub).
> 
> That's why I'm currently waiting to see if the ARM-runners of GitHub Actions mentioned in https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/ will become available outside of the private beta and what they will look like, to give our ARM options another look.

thanks for the detailed explanation. then i will use my own built arm64 image until the CI stuff is working properly :)

**Comment by adelton** [comment]
Nod, setting up your build pipeline is probably the best solution for now.

**Comment by clouds56** [comment]
> That's why I'm currently waiting to see if the ARM-runners of GitHub Actions mentioned in https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/ will become available outside of the private beta and what they will look like, to give our ARM options another look.

Now it's public beta, https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/, shall we reopen this?

**Comment by adelton** [comment]
I don't see ARM architecture available for the standard GitHub-hosted runners, only on the larger runners.

**Comment by abbra** [comment]
From the blog: "These runners are available to our customers on our GitHub Team and Enterprise Cloud plans. We expect to begin offering Arm runners for open source projects by the end of the year."

**Comment by brigriffin** [comment]
> I don't see ARM architecture available for the standard GitHub-hosted runners, only on the larger runners.

Hi @adelton, why don't you requests free arm runner credits from the Works from Arm initative here:

https://github.com/WorksOnArm/GitHub-Runners/issues

as stated here:

> Open Source Projects
> To provide open-source software projects with free credits to the Arm runners, we are expanding our [Works on Arm](https://worksonarm.com/) initiative that provides free access to Arm-based instances in the cloud to provide free credits. You can request access using the [Works on Arm GitHub repository](https://github.com/WorksOnArm/GitHub-Runners). Requests will be evaluated on a case-by-case basis for the duration and amount of credits to be issued.

Source: https://newsroom.arm.com/blog/github-arm-integration

**Comment by emmanuel** [comment]
Look at that, the key pre-requisite has arrived.

https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/

**Comment by adelton** [comment]
@emmanuel That announcement looks like a progress; I've been looking at those runners since the news landed.

Sadly the software set in the arm64 images is different from the x86_64 ones (for an example see https://github.com/actions/partner-runner-images/issues/30) making work with them more involved than I anticipated -- it is not a drop-in replacement. I'm also not sure what are the stages and possible (breaking) changes between the current Public Preview (in the partner runner images repo they call it Beta) and fully supported / GA state in the future.

**Comment by adelton** [comment]
Addition of building and pushing to registries of ARM64 images at least for the subset of the base operating systems is now proposed in https://github.com/freeipa/freeipa-container/pull/663.

**Comment by adelton** [comment]
Registries now contain `:almalinux-9` and `:rocky-9` tags as multiarch with ARM64 image.
